// <auto-generated />
using System;
using DataPostu;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataPostu.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240117112843_DodanieIdentity")]
    partial class DodanieIdentity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("DataPostu.Entities.PostEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Jan Kowalski",
                            Comment = "To jest pierwszy post na moim blogu!",
                            Content = "Pierwszy post na blogu",
                            Created = new DateTime(2024, 1, 17, 12, 28, 43, 44, DateTimeKind.Local).AddTicks(5608),
                            PublicationDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tags = "pierwszy, blog"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Anna Nowak",
                            Comment = "Drugi post na blogu z moimi przemyśleniami.",
                            Content = "Drugie post",
                            Created = new DateTime(2024, 1, 17, 12, 28, 43, 44, DateTimeKind.Local).AddTicks(5641),
                            PublicationDate = new DateTime(2021, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tags = "wprowadzenie, blog"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
